### ISSUE TITLE
lose the data when screen is rotated

### ISSUE THREAD

**Issue by vilgad** [KunalRaghav/CrossFire#11]
whenever i rotate the screen my score gets reset and i am back to square one

**Comment by vilgad** [comment]
i can solve this issue please assign it to me

**Comment by KunalRaghav** [comment]
@vilgad assigned the issue to you

**Comment by vilgad** [comment]
Thanks a lot

**Comment by AkshaiBaruah** [comment]
Hello ,I would like to solve this issue.

**Comment by vilgad** [comment]
> Hello ,I would like to solve this issue.

sorry but i am working in this issue

**Comment by KunalRaghav** [comment]
Fixed by @vilgad  so closing this issue
