### ISSUE TITLE
Use android viewBindings

### ISSUE THREAD

**Issue by KunalRaghav** [KunalRaghav/CrossFire#2]
Migrate from `findViewById` to android viewBindings in `MainActivity.kt`.

Note:
- Ensure no unnecessary dependencies are added
- `MainActivity.kt` and `activity_main.xml` have minimal changes made to it and are well-formatted before creating a PR.

**Comment by yoobi** [comment]
Hello, I'd like to work on this one

**Comment by KunalRaghav** [comment]
Okay @yoobi I'll assign it to you then

**Comment by yoobi** [comment]
You should consider using resource files for strings

**Comment by vilgad** [comment]
is this issue still open? i would like to solve it

**Comment by yoobi** [comment]
Hello the issue is already assigned  and solved

**Comment by vilgad** [comment]
> Hello the issue is already assigned and solved
ok

**Comment by vilgad** [comment]
i think the code has not been merged yet because view binding is not applied @yoobi @KunalRaghav

**Comment by yoobi** [comment]
Yes the pull request has not been merged, you can see all current pull request here: https://github.com/KunalRaghav/CrossFire/pulls

**Comment by vilgad** [comment]
Means i should fork your editing and then proceed or it will be ok if i fork original one @yoobi

**Comment by yoobi** [comment]
What are you trying to do ? If you are trying to fix an issue it's better to look in no PR are open for this issue, then fork the project and create your pull request

**Comment by vilgad** [comment]
I wanna add a question so what should I do for this

**Comment by yoobi** [comment]
Okay to add a question you need to:
1. Fork the project
2. Add your question in the Question.kt as specified in #1 
3. Push your code onto your forked project
4. Go to your forked project and click on "Create Pull Request"
5. Fill with a comment to say what you've changed and which issue you're fixing

That's it

**Comment by vilgad** [comment]
Thanks
