### ISSUE TITLE
Create an app icon for the app

### ISSUE THREAD

**Issue by KunalRaghav** [KunalRaghav/CrossFire#3]
Currently, the app doesn't have an icon and uses the default icon supplied by the android studio, please create one and add it to the project.

**Comment by durgeshahire07** [comment]
I would like to work on it. Can you assign it to me?

**Comment by vilgad** [comment]
can you assign me this issue please?
 this is my first open source issue

**Comment by KunalRaghav** [comment]
In that case then @durgeshahire07 and @vilgad both of you can create a mock up icons for the app and then proceed with the one the community votes for?

**Comment by vilgad** [comment]
Great

**Comment by durgeshahire07** [comment]
Okay, no problem!
