### ISSUE TITLE
Add a menu 

### ISSUE THREAD

**Issue by KunalRaghav** [KunalRaghav/CrossFire#4]
Currently, the app takes you straight to the questions, a landing screen/menu is needed that has the options play and exit.

| <h2>[CrossFire ❌🔥]</h2>| 
|:-----------:|
 | PLAY  | 
 | EXIT  |

**Comment by yoobi** [comment]
Hey can I take this issue ?

**Comment by KarandeepSingh15** [comment]
Hey There,
Can I take this issue?

**Comment by vilgad** [comment]
i would like to solve it please assign it to me
